

PROJECT_NAME := SRC

# Include the components directory of the main application:
#
EXTRA_COMPONENT_DIRS := $(realpath ../components)


TEST_COMPONENTS ?= src_libs

include $(IDF_PATH)/make/project.mk
